version: "3"

services:
  frontend:
    image: node:18.14.0
    container_name: frontend
    restart: always
    volumes:
      - ./frontend:/usr/src/app/frontend
      - frontend_node_modules:/usr/src/app/frontend/node_modules
    ports:
      - 3000:3000
    working_dir: /usr/src/app/frontend
    init: true
    command: bash -c "npm i && npm start"

  backend:
    image: node:18.14.0
    container_name: backend
    restart: always
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/usr/src/app/backend
    ports:
      - 12100:12100
    working_dir: /usr/src/app/backend
    env_file:
      - ./backend/prod.env
    init: true
    command: bash -c "npm i && npm start"

  backend_livekit:
    image: node:18.14.0
    container_name: backend_livekit
    restart: always
    ports:
      - 12150:12150
    env_file:
      - ./backend_livekit/prod.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend_livekit/:/usr/src/app/backend_livekit/
    working_dir: /usr/src/app/backend_livekit/
    init: true
    command: bash -c "npm i && npm start"

  livekit:
    image: livekit/livekit-server:v1.2.3
    container_name: livekit
    network_mode: "host"
    restart: always
    volumes:
      - ./livekit/livekit.prod.yaml:/etc/livekit.prod.yaml
    command: --config /etc/livekit.prod.yaml

  nginx:
    image: nginx:1.22.0
    container_name: nginx
    network_mode: "host"
    restart: always
    env_file:
      - ./nginx/prod.env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.https.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:arm64v8-v1.30.0
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: --version

volumes:
  frontend_node_modules:
