env:
  es2021: true
extends:
  - standard-with-typescript
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - filename-rules
rules:
  filename-rules/match: ['error', { .ts: camelCase }]
overrides:
  - files: '*.d.ts'
    rules:
      filename-rules/match: ['error', 'kebab-case']