env:
  es2021: true
extends:
  - plugin:import/recommended
  - plugin:import/typescript
  - standard-with-typescript
  - prettier
settings:
  import/resolver:
    typescript: {}
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - filename-rules
rules:
  filename-rules/match: ['error', { .ts: camelCase }]
  "@typescript-eslint/naming-convention": [
    'error',
    {
      "selector": ["method","function"],
      "format": ["camelCase"]
    }
  ]
  "@typescript-eslint/explicit-member-accessibility": 'warn'
  import/no-restricted-paths:
    - error
    - zones:
        - from:
            - './src/interactor'
            - './src/adapter'
            - './src/interface'
          target: './src/domain'
        - from:
            - './src/adapter'
            - './src/interface'
          target: './src/interactor'
        - from:
            - './src/interface'
          target: './src/adapter'
          except: ['./socket/action/actionTypes.ts', './socket/eventTypes.ts'] # 通信用の型は制限しない
overrides:
  - files: '*.d.ts'
    rules:
      filename-rules/match: ['error', 'kebab-case']
  # インタフェースは'IHogehoge.ts'なので例外
  - files: 'I*.ts'
    rules:
      filename-rules/match: ['error', 'PascalCase']
